spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/springbootdb
    username: root
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
server:
  port: 8081
  servlet:
    context-path: /stuman


